server:
  port: 10010
  tomcat:
    relaxed-query-chars: "="
    accesslog:
          enabled: true
          buffered: true
          prefix: access_log
          rotate: true
          suffix: .log
          max-days: 2
          pattern: "%h %l %u %t &quot;%r&quot; %s %b %{MG-Service-Id}i %{MG-User-Id}s"
spring:
  application:
    name: AuditGateway
  cloud:
    gateway:
      mvc:
        routes:
        #自定义的路由id，需要确保id的唯一
        - id: httpbin-service
          uri: http://httpbin.org
          predicates:
            - Header=MG-Service-Id, 1
          filters:
            - RemoveRequestHeader=MG-Service-Id
            
        - id: baidu-service
          uri: http://baidu.com
          predicates:
            - Header=MG-Service-Id, 2
            
        - id: user-service
          uri: http://127.0.0.1:8080
          predicates:
            - Header=MG-Service-Id, 99
          filters:
            - RemoveRequestHeader=MG-Service-Id #过滤请求头
            - RemoveResponseHeader=MG-user1 #过滤响应头
logging:
  level:
    root: info
    audit: debug